34-rails-validations-notes/config/routes.rb
Rails.application.routes.draw do
  get '/pets/about', to: 'pets#about', as: 'about'
  # get '/pets', to: 'pets#index'
  # get '/pets/new', to: 'pets#new'
  # get '/pets/:id', to: 'pets#show', as: "pet"
  # post '/pets', to: 'pets#create'

  # you could draw each route individually as above, but that can get tedious, hence the resources macro below
  resources :pets
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

34-rails-validations-notes/app/models/pet.rb
class Pet < ApplicationRecord


    SPECIES = ["cat", "dog", "fish"]

    validates(:name, {presence: true, uniqueness: true})
    validates :species, inclusion: {in: SPECIES, message: "%{value} is not a valid species"}
    validates :year_of_birth, numericality: {less_than_or_equal_to: Date.current.year}

    def age
        Date.current.year - self.year_of_birth
    end

    def to_s # this method monkey-patches Ruby's built-in to_s method, so that if you try to render a whole object in a substitution tag in a view <%= @pet %>, Rails will implicitly invoke this method
        "#{self.name} #{self.age}"
    end

end

34-rails-validations-notes/app/controllers/pets_controller.rb
class PetsController < ApplicationController

    before_action :find_pet, only: [:show, :edit, :update, :destroy]

    
    def index
        @pets = Pet.all
       
    end

    def show
        
    end

    def new
        @pet = Pet.new # since the new view is using form_for, must send 'blank' pet object to view
       
    end

    def create
        # if params[:pet][:name] != ""
        @pet = Pet.new(pet_params)
        if @pet.save
            redirect_to pet_path(@pet) # using the URL helper method for the show route
        else
            render :new
        end
    end

    def edit # actually, this whole action could be commented out, thanks to the before_action :find_pet and implicit rendering
    end
    
    def update
        if @pet.update(pet_params)
            flash[:success] = "Pet was updated!"
            redirect_to pet_path(@pet)
        else
            flash[:error] = @pet.errors.full_messages
            render :edit
        end
    end

    def destroy
        @pet.destroy
        redirect_to pets_path
    end

    private

    def pet_params
        params.require(:pet).permit(:name, :species, :year_of_birth, :good_with_kids)
    end

    def find_pet
        @pet = Pet.find(params[:id])
    end
end

34-rails-validations-notes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.any? %>
      <% flash.each do |type, msg| %>
        <div class=<%= type %>>
          <ul>
            <% if msg.is_a? Array%>
              <% msg.each do |m| %>
                <li><%= m %></li>
              <% end %>
            <% else%>
              <li><%=msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

34-rails-validations-notes/app/views/pets/edit.html.erb
<h1>Edit your pet!</h1>

<%= form_for @pet do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :species %>
    <%= f.text_field :species %>
    <%= f.label :year_of_birth %>
    <%= f.text_field :year_of_birth %>
    <%= f.label :good_with_kids, "Is good with kids: " %>
    <%= f.radio_button :good_with_kids, "true" %>
    <%= f.label :good_with_kids, "Is terrible with kids: " %>
    <%= f.radio_button :good_with_kids, "false" %>
    <%= f.submit %>
<% end %>

34-rails-validations-notes/app/views/pets/index.html.erb
<h1>Pets#index</h1>

<ul>
    <% @pets.each do |pet|%>
        <li><%= link_to pet.name, pet_path(pet) %></li>
    <% end %>
</ul>

<%= link_to "Create a pet", new_pet_path %>

34-rails-validations-notes/app/views/pets/new.html.erb
<h1>Add a new pet!</h1>

<% if @pet.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

    <ul>
      <% @pet.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @pet do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :species %>
    <%= f.text_field :species %>
    <%= f.label :year_of_birth %>
    <%= f.text_field :year_of_birth %>
    <%= f.label :good_with_kids, "Is good with kids: " %>
    <%= f.radio_button :good_with_kids, "true" %>
    <%= f.label :good_with_kids, "Is terrible with kids: " %>
    <%= f.radio_button :good_with_kids, "false" %>
    <%= f.submit %>
<% end %>

34-rails-validations-notes/app/views/pets/new_pet_form.html.erb
<h1>Add a new pet!</h1>

<%# <form method='post' action='/pets'>
    <input type='text'>
    <input type='submit'>

</form> %>

<%= form_tag pets_path do %>
    <div>
        <%= label_tag :name %>
        <%= text_field_tag :'pet[name]'%>
    </div>
    <div>
        <%= label_tag :species %>
        <%= text_field_tag :species %>
    </div>
    <div>
        <%= label_tag :year_of_birth %>
        <%= text_field_tag :year_of_birth %>
    </div>
    <div>
        <%= label_tag :good_with_kids %>
        <p>Is good with kids:</p>
        <%= radio_button_tag :good_with_kids, "true" %>
        <p>Is a monster with kids:</p>
        <%= radio_button_tag :good_with_kids, "false" %>
    </div>
    <%= submit_tag "Create a new pet" %>

<% end %>

34-rails-validations-notes/app/views/pets/show.html.erb
<h1>Pets#show</h1>

<p>Name: <%= @pet.name %></p>
<p>Species: <%= @pet.species %> | Age: <%= @pet.age %> </p>

<p>Good with kids? <%= @pet.good_with_kids ? "Terrific" : "Is a monster" %></p>

<button><%= link_to "Edit this pet", edit_pet_path(@pet) %></button>
<%= button_to "Delete", @pet, method: :delete %>
<%= link_to "Back", pets_path %>