35-rails-one-many-notes/config/routes.rb
Rails.application.routes.draw do
  resources :cows, only: [:new, :show, :create]
  resources :farmers, only: [:index, :show]
end

35-rails-one-many-notes/app/models/cow.rb
class Cow < ApplicationRecord
  belongs_to :farmer

  validates :name, { presence: true, uniqueness: true }
  validates :spots, numericality: { less_than_or_equal_to: 50 }
end

35-rails-one-many-notes/app/models/farmer.rb
class Farmer < ApplicationRecord
  has_many :cows, dependent: :destroy
end

35-rails-one-many-notes/app/controllers/cows_controller.rb
class CowsController < ApplicationController
  before_action :fetch_cow, only: [:show]

  def new
    @cow = Cow.new(spots: rand(0..25))
  end

  def show
    # calls fetch_cow
    render :show
  end

  def create
    @cow = Cow.create(cow_params)
    if @cow.save
      # redirect_to cow_path(@cow)
      redirect_to @cow
    else
      render :new
    end
  end

  private
  def cow_params
    params.require(:cow).permit(:name, :spots, :farmer_id)
  end

  def fetch_cow
    @cow = Cow.find(params[:id])
  end
end

35-rails-one-many-notes/app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  def index
    @farmers = Farmer.all
  end

  def show
    @farmer = Farmer.find(params[:id])
  end
end

35-rails-one-many-notes/app/helpers/cows_helper.rb
module CowsHelper
end

35-rails-one-many-notes/app/helpers/farmers_helper.rb
module FarmersHelper
end

35-rails-one-many-notes/app/views/cows/_form.html.erb
<%= form_for @cow do |f| %>
  <% if @cow.errors.any? %>
    <ul>
      <% @cow.errors.full_messages.map do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :spots %>
  <%= f.number_field :spots %>
  <br>
  <%= f.collection_select :farmer_id, Farmer.all, :id, :name %>
  <br>
  <%= f.submit %>
<% end %>

35-rails-one-many-notes/app/views/cows/new.html.erb
<h1>Create a Cow</h1>

<%# render partial: "form" %>

<%= form_for @cow do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :spots %>
    <%= f.number_field :spots %>
    <br>
    <select name="cow[farmer_id]">
        <% Farmer.all.each do |farmer|%>
            <option value="<%= farmer.id %>">
                <%= farmer.name %>
            </option>
        <% end %>
    </select>
    <%= f.submit %>
<% end %>

35-rails-one-many-notes/app/views/cows/show.html.erb
<h1>SHOW PAGE FOR OUR COWS</h1>
<h3>Name: <%= @cow.name %></h3>
<h3>Spots: <%= @cow.spots %></h3>
<h3>Farmer: <%= @cow.farmer.name %></h3>

<%= link_to "All Farmers", farmers_path %>
<br>
<%= link_to "Create A New Cow", new_cow_path %>

35-rails-one-many-notes/app/views/farmers/index.html.erb
<h1>All Farmers</h1>
<% @farmers.map do |farmer| %>
  <ul>
    <li><%= link_to farmer.name, farmer %></li>
  </ul>
<% end %>

35-rails-one-many-notes/app/views/farmers/show.html.erb
<h1>Farmer <%= @farmer.name %>'s Cows</h1>

<ul>
    <% @farmer.cows.each do |c| %>
        <li><%= c.name %></li>
    <% end %>
</ul>
<%= button_to "Delete", @farmer, method: :delete, data: {confirm: "Do you want to delete this farmer?"} %>