37-rails-recipe-allergen-notes/config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients, only: [:new, :create]
  resources :allergies, only: [:new, :create, :destroy]
  resources :ingredients, only: [:index, :show]
  resources :recipes
  resources :users, only: [:show, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

37-rails-recipe-allergen-notes/app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient

  validates :ingredient, uniqueness: {scope: :user}
end

37-rails-recipe-allergen-notes/app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
    has_many :allergies, dependent: :destroy
    has_many :users, through: :allergies
end

37-rails-recipe-allergen-notes/app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients

  MEAL_TYPES = ["Breakfast", "Lunch", "Dinner", "Appetizers", "Sweets"]

  validates :name, presence: true
  validates :meal_type, inclusion: {in: MEAL_TYPES}
end

37-rails-recipe-allergen-notes/app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  
  validates :measurement, presence: true
end

37-rails-recipe-allergen-notes/app/models/user.rb
class User < ApplicationRecord
    has_many :recipes, dependent: :destroy
    has_many :allergies, dependent: :destroy
    has_many :ingredients, through: :allergies

    validates :name, length: {minimum: 2}
end

37-rails-recipe-allergen-notes/app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController

    def new
        @allergy = Allergy.new
    end

    def create
        @allergy = Allergy.new(allergy_params)
        if @allergy.save
            redirect_to @allergy.user
        else
            render :new
        end
    end

    def destroy
        @allergy = Allergy.find(params[:id])
        @allergy.destroy
        redirect_to @allergy.user
    end

    private

    def allergy_params
        params.require(:allergy).permit(:user_id, :ingredient_id)
    end
end

37-rails-recipe-allergen-notes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

37-rails-recipe-allergen-notes/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    def index
        @ingredients = Ingredient.left_joins(:users).group(:id).order('count(users.id) DESC')
    end

    def show
        @ingredient = Ingredient.find(params[:id])
    end
end

37-rails-recipe-allergen-notes/app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController

    def new
        @recipe_ingredient = RecipeIngredient.new
        @recipes = Recipe.all
        @ingredients = Ingredient.all
    end

    def create
        @recipe_ingredient = RecipeIngredient.new(ri_params)
        if @recipe_ingredient.save
            redirect_to @recipe_ingredient.recipe

        else
            render :new
        end

    end

    private

    def ri_params
        params.require(:recipe_ingredient).permit(:measurement, :recipe_id, :ingredient_id)
    end
end

37-rails-recipe-allergen-notes/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    before_action :set_recipe, only: [:show, :edit, :update, :destroy]

    before_action :set_users, only: [:new, :create, :edit, :update]

    def index
        # byebug
        if params[:sort]
            @recipes = Recipe.all.sort_by {|r| r.ingredients.count}.reverse
        elsif params[:query]
            @recipes = Recipe.where('name LIKE ?', "%#{params[:query]}%")
            render :index
        else
            @recipes = Recipe.all
        end
    end
    
    def sorted
        @recipes = Recipe.all.sort_by {|r| r.ingredients.count}.reverse
        render :index
    end

    def show
    end
    
    def new
        @recipe = Recipe.new
    end
    
    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to @recipe
        else
            render :new
        end
    end
    
    def edit
        
    end
    
    def update
        if @recipe.update(recipe_params)
            redirect_to @recipe
        else
            render :edit
        end
    end
    
    def destroy
        @recipe.destroy
        redirect_to recipes_path
    end
    
    private

    def recipe_params
        params.require(:recipe).permit(:name, :meal_type, :user_id)
    end
    
    def set_recipe
        @recipe = Recipe.find(params[:id])
    end

    def set_users
        @users = User.all
    end

end

37-rails-recipe-allergen-notes/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :get_user

    def show

    end

    def destroy
        @user.destroy
        redirect_to recipes_path
    end

    private

    def get_user
        @user = User.find(params[:id])
    end
end

37-rails-recipe-allergen-notes/app/helpers/allergies_helper.rb
module AllergiesHelper
end

37-rails-recipe-allergen-notes/app/helpers/application_helper.rb
module ApplicationHelper
end

37-rails-recipe-allergen-notes/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

37-rails-recipe-allergen-notes/app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

37-rails-recipe-allergen-notes/app/helpers/recipes_helper.rb
module RecipesHelper
end

37-rails-recipe-allergen-notes/app/helpers/users_helper.rb
module UsersHelper
end

37-rails-recipe-allergen-notes/app/views/allergies/new.html.erb
<h1>Add an allergy</h1>

<%= form_for @allergy do |f| %>  
<% if @allergy.errors.any? %>
        <ul>
            <% @allergy.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %> 
    <%= f.label :user %>
    <%= f.collection_select :user_id, User.all, :id, :name %>
    <%= f.label :ingredient %>
    <%= f.collection_select :ingredient_id, Ingredient.all, :id, :name %>
    <%= f.submit %>
<% end %>

37-rails-recipe-allergen-notes/app/views/ingredients/index.html.erb
<h1>All the ingredients!</h1>

<ol>
    <% @ingredients.each do |i| %>
        <li><%= link_to i.name, i %> has <%= i.users.count%> people with allergies</li>
    <% end %>
</ol>

37-rails-recipe-allergen-notes/app/views/ingredients/show.html.erb
<h1>Ingredient: <%= @ingredient.name %></h1>

<h3><%= @ingredient.name %> appears in these recipes:</h3>

<ul>
    <% @ingredient.recipes.each do |r| %>
        <li><%= link_to r.name, r %></li>
    <% end %>
</ul>

<h3>Users allergic to <%= @ingredient.name %>:</h3>
<ul>
    <% @ingredient.users.each do |u| %>
        <li><%= link_to u.name, u %></li>
    <% end %>
</ul>

37-rails-recipe-allergen-notes/app/views/recipes/edit.html.erb
<h1>Edit <%= @recipe.name %></h1>

<%= form_for @recipe do |f| %>
    <% if @recipe.errors.any? %>
        <ul>
            <% @recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :meal_type, "Enter Breakfast, Lunch, Dinner, Appetizer or Sweet" %>
    <%= f.text_field :meal_type %>
    <%= f.collection_select :user_id, @users, :id, :name %>
    <%= f.submit %>
<% end %>

37-rails-recipe-allergen-notes/app/views/recipes/index.html.erb
<h1>All the recipes!</h1>

<ol>
    <% @recipes.each do |r| %>
        <li><%= link_to r.name, r %></li>
    <% end %>
</ol>

<%= form_with url: "/recipes", method: :get do |form| %>
  <%= form.label :query, "Search for:" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>

<%= form_tag recipes_path, method: :get do %>
    <%= submit_tag "Sort by number of ingreds", name: :sort %>
<% end %>
<p><%= link_to "Create a recipe", new_recipe_path %></p>

37-rails-recipe-allergen-notes/app/views/recipes/new.html.erb
<h1>Add a recipe</h1>

<%= form_for @recipe do |f| %>
    <% if @recipe.errors.any? %>
        <ul>
            <% @recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :meal_type, "Enter Breakfast, Lunch, Dinner, Appetizer or Sweet" %>
    <%= f.text_field :meal_type %>
    <%= f.collection_select :user_id, @users, :id, :name %>
    <%= f.submit %>
<% end %>

37-rails-recipe-allergen-notes/app/views/recipes/show.html.erb
<h1>Recipe: <%= @recipe.name %></h1>
<h2>Meal: <%= @recipe.meal_type %></h2>
<h3>by: <%= link_to @recipe.user.name, @recipe.user %></h3>

<h3>Ingredients: </h3>

<ul>
    <% @recipe.recipe_ingredients.each do |ri| %>
        <li><%= link_to ri.ingredient.name, ri.ingredient %>: <%= ri.measurement %></li>
    <% end %>
</ul>

<p><%= link_to "Add ingredient", new_recipe_ingredient_path %></p>
<p><%= link_to "Edit recipe", edit_recipe_path %></p>
<%= button_to "Delete this recipe", @recipe, method: :delete, data: {confirm: "Don't delete me!"} %>